name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: App Brickie
    steps:
      - uses: actions/checkout@v2
      - name: AppBrickie
        id: appBrickieBuild
        uses: DarthBenro008/app-brickie@v2.0
        with:
          type: "native"
          chatid: "bt8dkb05jhr8ila5hpf0"
          packagename: "com.ssindher11.todonotes"
      - name: Get Automated Result
        run: echo "${{ steps.appBrickieBuild.outputs.result }}"